version: '3.3'
services:
  mongo_db:
    image: mongo:${MONGO_DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./app/ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - 127.0.0.1:${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    build: ./app/post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./app/comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  back_net:
  front_net:
