apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.comment.name }}-service
spec:
  selector:
    app: {{ .Values.comment.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.commentServicePort }}
      targetPort: {{ .Values.env.commentServicePort }}
