apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}-service
spec:
  selector:
    app: {{ .Values.mongo.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.mongoDatabasePort }}
      targetPort: {{ .Values.env.mongoDatabasePort }}
