apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.post.name }}-service
spec:
  selector:
    app: {{ .Values.post.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.postServicePort }}
      targetPort: {{ .Values.env.postServicePort }}
