apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}-service
spec:
  selector:
    app: {{ .Values.ui.appLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.uiServicePort }}
      targetPort: {{ .Values.env.uiServicePort }}
