apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      # port: 27017
      # targetPort: 27017
